parser: '@typescript-eslint/parser'
extends:
  - 'plugin:@typescript-eslint/recommended'
parserOptions:
  ecmaVersion: 2018
plugins:
  - '@typescript-eslint'
rules:
  comma-dangle:
    - error
    - always-multiline
  eol-last:
    - error
  no-trailing-spaces:
    - error
  object-curly-spacing:
    - error
    - always
  prefer-const:
    - error
    - destructuring: 'all'
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
  space-infix-ops:
    - error
  space-unary-ops:
    - error
    - overrides:
        '!': true
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: 'none'
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/no-inferrable-types':
    - off
  '@typescript-eslint/no-non-null-assertion':
    - off
  '@typescript-eslint/no-unused-vars':
    - off
  '@typescript-eslint/semi':
    - error
    - never
